jenkins:
  systemMessage: "Cryptograss Jenkins Instance"
  numExecutors: 2
  scmCheckoutRetryCount: 2
  mode: NORMAL
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${JENKINS_ADMIN_PASSWORD}

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"

  nodes:
    - permanent:
        name: "built-in"
        remoteFS: "/var/jenkins_home"
        numExecutors: 2

jobs:
  - file: /var/jenkins_home/jobs/production.groovy
  - file: /var/jenkins_home/jobs/pull-requests.groovy

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-token"
              username: "jmyles"
              password: "${GITHUB_TOKEN}"
              description: "GitHub Token"
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "jenkins-ssh-key"
              username: "jenkins"
              privateKeySource:
                directEntry:
                  privateKey: ${JENKINS_SSH_KEY}
              description: "SSH key for rsync deployments"